In [1]:
import numpy as np
np.random.seed(42)
import random
random.seed(42)

import nltk, string
import matplotlib.pyplot as plt

from sklearn.datasets import fetch_20newsgroups


categories = ['comp.sys.ibm.pc.hardware', 'comp.graphics','comp.sys.mac.hardware', 'comp.os.ms-windows.misc','rec.autos', 'rec.motorcycles','rec.sport.baseball', 'rec.sport.hockey']
# added remove headers and footers
dataset = fetch_20newsgroups(subset='all', categories=categories, remove=('headers', 'footers'), shuffle=True, random_state=42)


In [4]:
#Question 1

from sklearn.feature_extraction.text import TfidfVectorizer

max_dfs = range(100, 1300, 200)

for x in max_dfs:
    tfidf_vect = TfidfVectorizer(stop_words='english',min_df=3, max_df=x)
    X_train_tfidf = tfidf_vect.fit_transform(dataset.data) 
    print('max_df = ', x, ' ', X_train_tfidf.shape)
    

max_df =  100   (7882, 22573)
max_df =  300   (7882, 23309)
max_df =  500   (7882, 23438)
max_df =  700   (7882, 23481)
max_df =  900   (7882, 23497)
max_df =  1100   (7882, 23506)


In [13]:
#Custom stop words
from sklearn.feature_extraction import text
from nltk.corpus import stopwords
import nltk
#nltk.download('stopwords')
from string import punctuation

stop_words_skt = text.ENGLISH_STOP_WORDS
stop_words_en = stopwords.words('english')
combined_stopwords = set.union(set(stop_words_en),set(stop_words_skt))

In [20]:
#Question 2
import pprint
pp = pprint.PrettyPrinter(indent=4)
from sklearn.cluster import KMeans
from sklearn.metrics.cluster import contingency_matrix, homogeneity_score, v_measure_score, completeness_score, adjusted_rand_score, adjusted_mutual_info_score

###################### Added max_df=500 ######################
tfidf_vect = TfidfVectorizer(stop_words='english', min_df=3, max_df=500)
X_train_tfidf = tfidf_vect.fit_transform(dataset.data) 

y_true = [int(i/4) for i in dataset.target]

km = KMeans(n_clusters=2, random_state=0, max_iter=1000, n_init=30)
y_pred = km.fit_predict(X_train_tfidf)
con_mat = contingency_matrix(y_true,y_pred)
pp.pprint(con_mat)

print("Homogeneity score: ", homogeneity_score(y_true,y_pred))
print("Completeness score: ",completeness_score(y_true,y_pred))
print("V-measure score: ",v_measure_score(y_true,y_pred))
print("Adjusted Rand score: ",adjusted_rand_score(y_true,y_pred))
print("Adjusted mutual information score: ",adjusted_mutual_info_score(y_true,y_pred))

array([[3132,  771],
       [  13, 3966]])
Homogeneity score:  0.5993795768773826
Completeness score:  0.6176408341238924
V-measure score:  0.6083732014236275
Adjusted Rand score:  0.64166131789866
Adjusted mutual information score:  0.6083368094597101


In [19]:
###################### Added combined_stopwords instead of 'english' ######################


tfidf_vect = TfidfVectorizer(stop_words=combined_stopwords, min_df=3, max_df=500)
X_train_tfidf = tfidf_vect.fit_transform(dataset.data) 

y_true = [int(i/4) for i in dataset.target]

km = KMeans(n_clusters=2, random_state=0, max_iter=1000, n_init=30)
y_pred = km.fit_predict(X_train_tfidf)
con_mat = contingency_matrix(y_true,y_pred)
pp.pprint(con_mat)

print("Homogeneity score: ", homogeneity_score(y_true,y_pred))
print("Completeness score: ",completeness_score(y_true,y_pred))
print("V-measure score: ",v_measure_score(y_true,y_pred))
print("Adjusted Rand score: ",adjusted_rand_score(y_true,y_pred))
print("Adjusted mutual information score: ",adjusted_mutual_info_score(y_true,y_pred))

array([[3171,  732],
       [  14, 3965]])
Homogeneity score:  0.6114957858564866
Completeness score:  0.628234793451931
V-measure score:  0.6197522834978887
Adjusted Rand score:  0.6572043026994028
Adjusted mutual information score:  0.6197170012943365


In [22]:
###################### combined_stopwords & max_df=300 ######################

tfidf_vect = TfidfVectorizer(stop_words=combined_stopwords, min_df=3, max_df=300)
X_train_tfidf = tfidf_vect.fit_transform(dataset.data) 

y_true = [int(i/4) for i in dataset.target]

km = KMeans(n_clusters=2, random_state=0, max_iter=1000, n_init=30)
y_pred = km.fit_predict(X_train_tfidf)
con_mat = contingency_matrix(y_true,y_pred)
pp.pprint(con_mat)

print("Homogeneity score: ", homogeneity_score(y_true,y_pred))
print("Completeness score: ",completeness_score(y_true,y_pred))
print("V-measure score: ",v_measure_score(y_true,y_pred))
print("Adjusted Rand score: ",adjusted_rand_score(y_true,y_pred))
print("Adjusted mutual information score: ",adjusted_mutual_info_score(y_true,y_pred))

array([[3634,  269],
       [3979,    0]])
Homogeneity score:  0.03549503601115764
Completeness score:  0.16531999071517453
V-measure score:  0.05844223033962738
Adjusted Rand score:  0.005971394939181551
Adjusted mutual information score:  0.05830005626738529


In [23]:
###################### combined_stopwords & max_df=700 ######################

tfidf_vect = TfidfVectorizer(stop_words=combined_stopwords, min_df=3, max_df=700)
X_train_tfidf = tfidf_vect.fit_transform(dataset.data) 

y_true = [int(i/4) for i in dataset.target]

km = KMeans(n_clusters=2, random_state=0, max_iter=1000, n_init=30)
y_pred = km.fit_predict(X_train_tfidf)
con_mat = contingency_matrix(y_true,y_pred)
pp.pprint(con_mat)

print("Homogeneity score: ", homogeneity_score(y_true,y_pred))
print("Completeness score: ",completeness_score(y_true,y_pred))
print("V-measure score: ",v_measure_score(y_true,y_pred))
print("Adjusted Rand score: ",adjusted_rand_score(y_true,y_pred))
print("Adjusted mutual information score: ",adjusted_mutual_info_score(y_true,y_pred))

array([[ 616, 3287],
       [3951,   28]])
Homogeneity score:  0.6397453596391968
Completeness score:  0.6516124267310988
V-measure score:  0.6456243663596427
Adjusted Rand score:  0.6998444972085943
Adjusted mutual information score:  0.645591624788936


In [24]:
###################### combined_stopwords & max_df=800 ######################

tfidf_vect = TfidfVectorizer(stop_words=combined_stopwords, min_df=3, max_df=800)
X_train_tfidf = tfidf_vect.fit_transform(dataset.data) 

y_true = [int(i/4) for i in dataset.target]

km = KMeans(n_clusters=2, random_state=0, max_iter=1000, n_init=30)
y_pred = km.fit_predict(X_train_tfidf)
con_mat = contingency_matrix(y_true,y_pred)
pp.pprint(con_mat)

print("Homogeneity score: ", homogeneity_score(y_true,y_pred))
print("Completeness score: ",completeness_score(y_true,y_pred))
print("V-measure score: ",v_measure_score(y_true,y_pred))
print("Adjusted Rand score: ",adjusted_rand_score(y_true,y_pred))
print("Adjusted mutual information score: ",adjusted_mutual_info_score(y_true,y_pred))

###################### BEST SCORES ######################


array([[ 601, 3302],
       [3946,   33]])
Homogeneity score:  0.6410847357002711
Completeness score:  0.6522100862434727
V-measure score:  0.6465995589962014
Adjusted Rand score:  0.7040970263913902
Adjusted mutual information score:  0.6465669265420472


In [25]:
###################### combined_stopwords & max_df=900 ######################

tfidf_vect = TfidfVectorizer(stop_words=combined_stopwords, min_df=3, max_df=900)
X_train_tfidf = tfidf_vect.fit_transform(dataset.data) 

y_true = [int(i/4) for i in dataset.target]

km = KMeans(n_clusters=2, random_state=0, max_iter=1000, n_init=30)
y_pred = km.fit_predict(X_train_tfidf)
con_mat = contingency_matrix(y_true,y_pred)
pp.pprint(con_mat)

print("Homogeneity score: ", homogeneity_score(y_true,y_pred))
print("Completeness score: ",completeness_score(y_true,y_pred))
print("V-measure score: ",v_measure_score(y_true,y_pred))
print("Adjusted Rand score: ",adjusted_rand_score(y_true,y_pred))
print("Adjusted mutual information score: ",adjusted_mutual_info_score(y_true,y_pred))

array([[ 855, 3048],
       [3967,   12]])
Homogeneity score:  0.5731736628163333
Completeness score:  0.5947573899996839
V-measure score:  0.5837660894301141
Adjusted Rand score:  0.6083588906174414
Adjusted mutual information score:  0.5837272782988524


In [21]:
###################### combined_stopwords & max_df=1000 ######################

tfidf_vect = TfidfVectorizer(stop_words=combined_stopwords, min_df=3, max_df=1000)
X_train_tfidf = tfidf_vect.fit_transform(dataset.data) 

y_true = [int(i/4) for i in dataset.target]

km = KMeans(n_clusters=2, random_state=0, max_iter=1000, n_init=30)
y_pred = km.fit_predict(X_train_tfidf)
con_mat = contingency_matrix(y_true,y_pred)
pp.pprint(con_mat)

print("Homogeneity score: ", homogeneity_score(y_true,y_pred))
print("Completeness score: ",completeness_score(y_true,y_pred))
print("V-measure score: ",v_measure_score(y_true,y_pred))
print("Adjusted Rand score: ",adjusted_rand_score(y_true,y_pred))
print("Adjusted mutual information score: ",adjusted_mutual_info_score(y_true,y_pred))

array([[3138,  765],
       [  17, 3962]])
Homogeneity score:  0.597583736687478
Completeness score:  0.6153179590564624
V-measure score:  0.6063211990124888
Adjusted Rand score:  0.6424747234997527
Adjusted mutual information score:  0.6062846302021816
